### PR TITLE
Remove wrf=? to correct issue with X-Content-Type-Options=nosniff

### PR DESCRIPTION
**Pull request by JEBailey**
Removing for two reasons. First is that we did this to correct an issue where, the response was being returned back with the mimetype of text/plain and an X-Content-Type-Options=nosniff. This was generating an error because the nosniff option was forcing the browser client to accept the mimetype being sent back as canonical while, at the same time not being able to execute the jsonp since the mimetype of plain text was considered not executable.

There are a number of places that this could be corrected, however it became apparent that appending this value to the end of this ajax request was not needed. JQuery already has functionality to handle jsonp and a built in callback mechanism, neither are needed or used in the current scenario. What is happening is that JQuery see's that there is a '?' at the end of the query, assumes that you want to do a jsonp callback, since you haven't provided a callback, JQuery inserts a reference to it's own handler and sends that reference appended to the end of the query. When Solr gets this value, it's converting the response into a jsonp response which adds an additional step that's not needed.

### CODE REVIEW

**Comment by jpmckinney** [comment]
`json.wrf` is used to trigger JSONP (which is [by design](https://wiki.apache.org/solr/SolJSON)). Without it, you'll run into cross-domain errors, unless your proxy/Solr is on the same domain.

**Comment by jpmckinney** [comment]
What's returning text/plain and X-Content-Type-Options=nosniff?

**Comment by JEBailey** [comment]
Our entire infrastructure for web content has been migrating over to the OWASP standard recommendations for headers which include setting of the X-Content-Type-Options=nosniff. Technically we're hitting a lucidworks fusion endpoint. So I can say with certainty whether solr's wrapped response is coming back as json or not.

Since the dataType was being set to json rather than jsonp I had assumed that jQuery's fallback to using jsonp when a question mark is at the end, was not deliberate.  Would it be better if we extended the function signature to include a flag as to whether jsonp was desired.

```function (servlet, string, handler, errorHandler, disableJsonp)```

that way jsonp would be used by default and there wouldn't be a change to anyone's experience.

**Comment by jpmckinney** [comment]
Can you write a pull request?

**Comment by JEBailey** [comment]
Sure thing

**Comment by JEBailey** [comment]
closing to create new pr to prevent confusion over my poor git fu

**Pull request closed without merging**
